"""IR to SeptaASM code generator for SeptaLang v0.1.

Transforms an IRProgram into assembly text. Uses static memory slots
for all variables; no register allocator.

Register convention:
  R0  — return value
  R1  — argument 1 / scratch for ARG
  R2  — argument 2 / scratch for ARG
  R3  — argument 3 / scratch for ARG
  R4  — primary scratch (left operand, general use)
  R5  — secondary scratch (right operand)
  R6  — tertiary scratch (comparison results, extra)

Every IR slot has a fixed memory address. Operands are loaded from
memory into scratch registers, operated on, and stored back.

Public API:
  generate(program: IRProgram) -> str
"""

from septa.codegen.addresses import AddressMap, allocate
from septa.common.errors import CodegenError
from septa.ir.ir import Instr, IRFunction, IRProgram, Op

# Scratch registers
_R4 = "R4"
_R5 = "R5"
_R6 = "R6"

# Conditional jump opcode for each comparison IR op
_CMP_JUMPS: dict[Op, str] = {
    Op.CMP_EQ: "JZ",
    Op.CMP_NE: "JNZ",
    Op.CMP_GT: "JG",
    Op.CMP_LT: "JL",
    Op.CMP_GE: "JGE",
    Op.CMP_LE: "JLE",
}

# Arg index -> register name
_ARG_REGS = {0: "R1", 1: "R2", 2: "R3"}


def generate(program: IRProgram) -> str:
    """Generate SeptaASM text from an IRProgram."""
    return _Codegen(program).run()


class _Codegen:
    def __init__(self, program: IRProgram) -> None:
        self._program = program
        self._addrs = allocate(program)
        self._lines: list[str] = []
        self._cg_counter = 0  # synthetic label counter
        self._current_fn = ""  # current function being emitted

    def run(self) -> str:
        self._emit_header()
        self._emit_init()
        for fn in self._program.functions:
            self._emit_function(fn)
        return "\n".join(self._lines) + "\n"

    # --- helpers ---

    def _emit(self, line: str) -> None:
        self._lines.append(line)

    def _emit_instr(self, text: str) -> None:
        self._lines.append(f"    {text}")

    def _emit_label(self, name: str) -> None:
        self._lines.append(f"{name}:")

    def _new_cg_label(self) -> str:
        label = f"_cg{self._cg_counter}"
        self._cg_counter += 1
        return label

    def _slot_addr(self, slot: str) -> int:
        return self._addrs.addr(slot, self._current_fn)

    def _fn_label(self, label: str) -> str:
        """Prefix an IR label with current function name for uniqueness."""
        return f"{self._current_fn}.{label}"

    # --- program structure ---

    def _emit_header(self) -> None:
        self._emit("; SeptaASM generated by SeptaLang compiler v0.1")
        # Emit address map as comments for debugging
        for g in self._program.globals:
            addr = self._addrs.global_addrs[g.slot]
            self._emit(f"; global {g.name} @ {addr} = {g.init_value}")
        for fn in self._program.functions:
            fn_map = self._addrs.fn_addrs.get(fn.name, {})
            if fn_map:
                slots_desc = ", ".join(
                    f"{s}@{a}" for s, a in fn_map.items()
                )
                self._emit(f"; fn {fn.name}: {slots_desc}")
            else:
                self._emit(f"; fn {fn.name}: (no slots)")
        self._emit("")

    def _emit_init(self) -> None:
        """Emit the _init block: initialize globals, call main, halt."""
        self._emit_label("_init")
        # Initialize globals
        for g in self._program.globals:
            addr = self._addrs.global_addrs[g.slot]
            self._emit_instr(f"LI {_R4}, {g.init_value}")
            self._emit_instr(f"ST {_R4}, [{addr}]")
        # Call main and halt
        self._emit_instr("CALL main")
        self._emit_instr("HALT")
        self._emit("")

    def _emit_function(self, fn: IRFunction) -> None:
        self._current_fn = fn.name
        self._emit_label(fn.name)

        # Function prologue: copy arg registers to param slots
        for i, param_slot in enumerate(fn.params):
            if i > 2:
                raise CodegenError(
                    f"function '{fn.name}' has more than 3 parameters"
                )
            addr = self._slot_addr(param_slot)
            self._emit_instr(f"ST {_ARG_REGS[i]}, [{addr}]")

        # Emit body
        for instr in fn.body:
            self._emit_ir(instr)

        self._emit("")

    # --- IR instruction dispatch ---

    def _emit_ir(self, instr: Instr) -> None:
        op = instr.op
        if op is Op.CONST:
            self._emit_const(instr)
        elif op is Op.COPY:
            self._emit_copy(instr)
        elif op in (Op.ADD, Op.SUB):
            self._emit_arith(instr)
        elif op is Op.NEG:
            self._emit_neg(instr)
        elif op is Op.NOT:
            self._emit_not(instr)
        elif op in _CMP_JUMPS:
            self._emit_cmp(instr)
        elif op is Op.MEM_LOAD:
            self._emit_mem_load(instr)
        elif op is Op.MEM_STORE:
            self._emit_mem_store(instr)
        elif op is Op.LABEL:
            self._emit_ir_label(instr)
        elif op is Op.JUMP:
            self._emit_jump(instr)
        elif op in (Op.JUMP_Z, Op.JUMP_NZ):
            self._emit_cond_jump(instr)
        elif op is Op.ARG:
            self._emit_arg(instr)
        elif op is Op.CALL:
            self._emit_call(instr)
        elif op is Op.RETURN:
            self._emit_return(instr)
        elif op is Op.RETURN_VOID:
            self._emit_instr("RET")
        elif op is Op.PRINT:
            self._emit_print(instr)
        elif op is Op.PRINTD:
            self._emit_printd(instr)
        elif op is Op.HALT:
            self._emit_instr("HALT")

    # --- individual IR ops ---

    def _emit_const(self, instr: Instr) -> None:
        addr = self._slot_addr(instr.dst)
        self._emit_instr(f"LI {_R4}, {instr.imm}")
        self._emit_instr(f"ST {_R4}, [{addr}]")

    def _emit_copy(self, instr: Instr) -> None:
        src_addr = self._slot_addr(instr.src)
        dst_addr = self._slot_addr(instr.dst)
        self._emit_instr(f"LD {_R4}, [{src_addr}]")
        self._emit_instr(f"ST {_R4}, [{dst_addr}]")

    def _emit_arith(self, instr: Instr) -> None:
        src_addr = self._slot_addr(instr.src)
        src2_addr = self._slot_addr(instr.src2)
        dst_addr = self._slot_addr(instr.dst)
        asm_op = "ADD" if instr.op is Op.ADD else "SUB"
        self._emit_instr(f"LD {_R4}, [{src_addr}]")
        self._emit_instr(f"LD {_R5}, [{src2_addr}]")
        self._emit_instr(f"{asm_op} {_R4}, {_R4}, {_R5}")
        self._emit_instr(f"ST {_R4}, [{dst_addr}]")

    def _emit_neg(self, instr: Instr) -> None:
        src_addr = self._slot_addr(instr.src)
        dst_addr = self._slot_addr(instr.dst)
        self._emit_instr(f"LI {_R4}, 0")
        self._emit_instr(f"LD {_R5}, [{src_addr}]")
        self._emit_instr(f"SUB {_R4}, {_R4}, {_R5}")
        self._emit_instr(f"ST {_R4}, [{dst_addr}]")

    def _emit_not(self, instr: Instr) -> None:
        """NOT: dst = (src == 0) ? 6 : 0"""
        src_addr = self._slot_addr(instr.src)
        dst_addr = self._slot_addr(instr.dst)
        true_label = self._new_cg_label()
        end_label = self._new_cg_label()
        self._emit_instr(f"LD {_R4}, [{src_addr}]")
        self._emit_instr(f"LI {_R5}, 0")
        self._emit_instr(f"CMP {_R4}, {_R5}")
        self._emit_instr(f"JZ {true_label}")
        self._emit_instr(f"LI {_R4}, 0")
        self._emit_instr(f"JMP {end_label}")
        self._emit_label(true_label)
        self._emit_instr(f"LI {_R4}, 6")
        self._emit_label(end_label)
        self._emit_instr(f"ST {_R4}, [{dst_addr}]")

    def _emit_cmp(self, instr: Instr) -> None:
        """Comparison: dst = (src OP src2) ? 6 : 0"""
        src_addr = self._slot_addr(instr.src)
        src2_addr = self._slot_addr(instr.src2)
        dst_addr = self._slot_addr(instr.dst)
        jump_op = _CMP_JUMPS[instr.op]
        true_label = self._new_cg_label()
        end_label = self._new_cg_label()
        self._emit_instr(f"LD {_R4}, [{src_addr}]")
        self._emit_instr(f"LD {_R5}, [{src2_addr}]")
        self._emit_instr(f"CMP {_R4}, {_R5}")
        self._emit_instr(f"{jump_op} {true_label}")
        self._emit_instr(f"LI {_R4}, 0")
        self._emit_instr(f"JMP {end_label}")
        self._emit_label(true_label)
        self._emit_instr(f"LI {_R4}, 6")
        self._emit_label(end_label)
        self._emit_instr(f"ST {_R4}, [{dst_addr}]")

    def _emit_mem_load(self, instr: Instr) -> None:
        """MEM_LOAD: dst = memory[src] (indirect load)."""
        src_addr = self._slot_addr(instr.src)
        dst_addr = self._slot_addr(instr.dst)
        self._emit_instr(f"LD {_R4}, [{src_addr}]")
        self._emit_instr(f"LDR {_R5}, [{_R4}]")
        self._emit_instr(f"ST {_R5}, [{dst_addr}]")

    def _emit_mem_store(self, instr: Instr) -> None:
        """MEM_STORE: memory[dst] = src (indirect store)."""
        dst_addr = self._slot_addr(instr.dst)
        src_addr = self._slot_addr(instr.src)
        self._emit_instr(f"LD {_R4}, [{dst_addr}]")
        self._emit_instr(f"LD {_R5}, [{src_addr}]")
        self._emit_instr(f"STR {_R5}, [{_R4}]")

    def _emit_ir_label(self, instr: Instr) -> None:
        self._emit_label(self._fn_label(instr.label))

    def _emit_jump(self, instr: Instr) -> None:
        self._emit_instr(f"JMP {self._fn_label(instr.label)}")

    def _emit_cond_jump(self, instr: Instr) -> None:
        """JUMP_Z/JUMP_NZ: branch if slot is zero/non-zero."""
        src_addr = self._slot_addr(instr.src)
        target = self._fn_label(instr.label)
        asm_jump = "JZ" if instr.op is Op.JUMP_Z else "JNZ"
        self._emit_instr(f"LD {_R4}, [{src_addr}]")
        self._emit_instr(f"LI {_R5}, 0")
        self._emit_instr(f"CMP {_R4}, {_R5}")
        self._emit_instr(f"{asm_jump} {target}")

    def _emit_arg(self, instr: Instr) -> None:
        """ARG: load slot into the correct argument register."""
        reg = _ARG_REGS.get(instr.imm)
        if reg is None:
            raise CodegenError(
                f"argument index {instr.imm} exceeds max 3 (R1-R3)"
            )
        src_addr = self._slot_addr(instr.src)
        self._emit_instr(f"LD {reg}, [{src_addr}]")

    def _emit_call(self, instr: Instr) -> None:
        self._emit_instr(f"CALL {instr.label}")
        if instr.dst:
            dst_addr = self._slot_addr(instr.dst)
            self._emit_instr(f"ST R0, [{dst_addr}]")

    def _emit_return(self, instr: Instr) -> None:
        src_addr = self._slot_addr(instr.src)
        self._emit_instr(f"LD R0, [{src_addr}]")
        self._emit_instr("RET")

    def _emit_print(self, instr: Instr) -> None:
        src_addr = self._slot_addr(instr.src)
        self._emit_instr(f"LD {_R4}, [{src_addr}]")
        self._emit_instr(f"PRINT {_R4}")

    def _emit_printd(self, instr: Instr) -> None:
        src_addr = self._slot_addr(instr.src)
        self._emit_instr(f"LD {_R4}, [{src_addr}]")
        self._emit_instr(f"PRINTD {_R4}")
